spring:
  datasource:
    url: jdbc:postgresql://db:5432/toktot
    username: toktot_user
    password: toktot_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.toktot: INFO
  file:
    name: /app/logs/toktot.log