# 기본 설정
spring:
  application:
    name: toktot

  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/toktot
    username: toktot_user
    password: toktot_password
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate  # 운영환경에서는 validate 사용
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  # SQL 초기화 설정
  sql:
    init:
      mode: never  # 운영환경에서는 never 사용

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

# 로깅 설정
logging:
  level:
    com.toktot: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정 (헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

---
# 개발 환경 설정
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    com.toktot: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Docker 환경 설정
spring:
  config:
    activate:
      on-profile: docker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.toktot: INFO
    root: INFO

---
# 운영 환경 설정
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  sql:
    init:
      mode: never

logging:
  level:
    com.toktot: WARN
    root: WARN
  file:
    name: logs/toktot.log